export const fromLanguages: Record<string, string> = {
	AUTO: 'Detect language',
	BG: 'Bulgarian',
	CS: 'Czech',
	DA: 'Danish',
	DE: 'German',
	EL: 'Greek',
	EN: 'English',
	ES: 'Spanish',
	ET: 'Estonian',
	FI: 'Finnish',
	FR: 'French',
	HU: 'Hungarian',
	ID: 'Indonesian',
	IT: 'Italian',
	JA: 'Japanese',
	KO: 'Korean',
	LT: 'Lithuanian',
	LV: 'Latvian',
	NL: 'Dutch',
	PL: 'Polish',
	PT: 'Portuguese',
	RO: 'Romanian',
	RU: 'Russian',
	SK: 'Slovak',
	SL: 'Slovenian',
	SV: 'Swedish',
	TR: 'Turkish',
	UK: 'Ukrainian',
	ZH: 'Chinese'
};

export const toLanguageAliases: Record<string, string> = {
	EN: 'EN-GB',
	PT: 'PT-PT'
};

export const toLanguages: Record<string, string> = {
	BG: 'Bulgarian',
	CS: 'Czech',
	DA: 'Danish',
	DE: 'German',
	EL: 'Greek',
	'EN-GB': 'English (British)',
	'EN-US': 'English (American)',
	ES: 'Spanish',
	ET: 'Estonian',
	FI: 'Finnish',
	FR: 'French',
	HU: 'Hungarian',
	ID: 'Indonesian',
	IT: 'Italian',
	JA: 'Japanese',
	KO: 'Korean',
	LT: 'Lithuanian',
	LV: 'Latvian',
	NL: 'Dutch',
	PL: 'Polish',
	'PT-BR': 'Portuguese (Brazilian)',
	'PT-PT': 'Portuguese (European)',
	RO: 'Romanian',
	RU: 'Russian',
	SK: 'Slovak',
	SL: 'Slovenian',
	SV: 'Swedish',
	TR: 'Turkish',
	UK: 'Ukrainian',
	ZH: 'Chinese (simplified)'
};
